name: Install and Display TeamViewer ID and Password

on:
  workflow_dispatch:

jobs:
  get-teamviewer-id-and-password:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeamViewer
      run: |
        Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewer_Setup.exe" -OutFile "$env:USERPROFILE\Downloads\TeamViewer_Setup.exe"
        Start-Process -FilePath "$env:USERPROFILE\Downloads\TeamViewer_Setup.exe" -ArgumentList "/S" -NoNewWindow -Wait

    - name: Set TeamViewer Password
      run: |
        $teamviewerPath = "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
        if (-Not (Test-Path $teamviewerPath)) {
          $teamviewerPath = "C:\Program Files\TeamViewer\TeamViewer.exe"
        }
        if (Test-Path $teamviewerPath) {
          & "$teamviewerPath" --Password "YourSecurePassword"
        }
        
    - name: Verify TeamViewer Installation
      run: |
        $teamviewerPath = "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
        if (-Not (Test-Path $teamviewerPath)) {
          $teamviewerPath = "C:\Program Files\TeamViewer\TeamViewer.exe"
        }
        if (-Not (Test-Path $teamviewerPath)) {
          Write-Output "TeamViewer is not installed."
          exit 1
        }

    - name: Get TeamViewer ID
      run: |
        $teamviewerPath = "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
        if (-Not (Test-Path $teamviewerPath)) {
          $teamviewerPath = "C:\Program Files\TeamViewer\TeamViewer.exe"
        }
        Start-Process -FilePath $teamviewerPath -ArgumentList "--info" -NoNewWindow -Wait -PassThru
        Start-Sleep -Seconds 10
        $logFile = "$env:ProgramData\TeamViewer\TeamViewer14_Logfile.log"
        $id = Get-Content $logFile | Select-String -Pattern "Your ID" | ForEach-Object { $_.Line.Split(':')[1].Trim() }
        Write-Output "TeamViewer ID: $id"
        Write-Output "TeamViewer Password: YourSecurePassword"

    - name: Display TeamViewer Log
      run: |
        $logFile = "$env:ProgramData\TeamViewer\TeamViewer14_Logfile.log"
        if (Test-Path $logFile) {
          Get-Content $logFile
        } else {
          Write-Output "Log file not found."
        }
