name: Get TeamViewer ID and Password

on:
  push:
    branches:
      - main

jobs:
  get-teamviewer-id:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeamViewer
      run: |
        Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewer_Setup.exe" -OutFile "$env:USERPROFILE\Downloads\TeamViewer_Setup.exe"
        Start-Process -FilePath "$env:USERPROFILE\Downloads\TeamViewer_Setup.exe" -ArgumentList "/S" -NoNewWindow -Wait

    - name: Set TeamViewer Password
      run: |
        $teamviewerPath = "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
        if (-Not (Test-Path $teamviewerPath)) {
          $teamviewerPath = "C:\Program Files\TeamViewer\TeamViewer.exe"
        }
        if (Test-Path $teamviewerPath) {
          & "$teamviewerPath" --Password "YourSecurePassword"
        } else {
          Write-Output "TeamViewer is not installed."
          exit 1
        }

    - name: Get TeamViewer ID
      run: |
        $teamviewerPath = "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
        if (-Not (Test-Path $teamviewerPath)) {
          $teamviewerPath = "C:\Program Files\TeamViewer\TeamViewer.exe"
        }
        if (Test-Path $teamviewerPath) {
          $id = & "$teamviewerPath" --info | Select-String -Pattern "Your ID" | ForEach-Object { $_.Line.Split(':')[1].Trim() }
          Write-Output "TeamViewer ID: $id"
          Write-Output "TeamViewer Password: YourSecurePassword"
        } else {
          Write-Output "TeamViewer is not installed."
          exit 1
        }
