name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Download playit.gg MSI
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86_64.msi" -OutFile "$env:USERPROFILE\Downloads\playit-windows.msi"

    - name: Install playit.gg
      run: |
        Start-Process msiexec.exe -ArgumentList "/i", "$env:USERPROFILE\Downloads\playit-windows.msi", "/quiet", "/norestart" -NoNewWindow -Wait

    - name: Check installation directory
      run: |
        if (Test-Path "C:\Program Files\playit_gg\bin\playit.exe") {
          Write-Output "playit.gg installed successfully"
          Get-ChildItem "C:\Program Files\playit_gg\bin" -Recurse
        } else {
          Write-Output "playit.gg installation failed"
          exit 1

    - name: Run playit.gg
      run: |
        Start-Process -FilePath "C:\Program Files\playit_gg\bin\playit.exe" -NoNewWindow
